#!/usr/bin/env bash

set -euo pipefail

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 output/file.json [output/another.json ...]" >&2
  exit 1
fi

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"
template_dir="${repo_root}/newlayout-lua"
which_json_file="${template_dir}/whichJson.tex"
cache_root="${template_dir}/.texcache"
mkdir -p "${cache_root}/texmf-cache" "${cache_root}/texmf-var"

render_one() {
  local json_input="$1"
  local json_path
  local json_dir
  local json_file
  local pdf_output

  if [ ! -f "$json_input" ]; then
    echo "JSON file not found: ${json_input}" >&2
    exit 1
  fi

  json_path="$(cd "$(dirname "$json_input")" && pwd)/$(basename "$json_input")"
  json_dir="$(dirname "$json_path")"
  json_file="$(basename "$json_path")"
  pdf_output="${json_path%.json}.pdf"

  cat >"${which_json_file}" <<EOF
% Generated by scripts/render-json-to-pdf.sh. Do not edit manually.
\newcommand{\JsonDataDir}{${json_dir}}
\newcommand{\JsonDataFileName}{${json_file}}
EOF

  echo "Rendering ${json_file} -> $(basename "${pdf_output}")"
  (
    cd "${template_dir}"
    export HOME="${cache_root}"
    export XDG_CACHE_HOME="${cache_root}"
    export TMPDIR="${cache_root}"
    rm -f main.pdf
    lualatex -interaction=nonstopmode -halt-on-error -file-line-error main.tex
  )

  mv -f "${template_dir}/main.pdf" "${pdf_output}"
}

for json_file in "$@"; do
  render_one "${json_file}"
done
